#pragma once

#include "include.hpp"
#include "Location.hpp"
#include "Server.hpp"
#include "Config.hpp"
#include "WebServ.hpp"
#include "Request.hpp"
#include "Document.hpp"
#include "RequestMaker.hpp"
#include "RequestProcessor.hpp"
#include "Response.hpp"
#include "ResponseSender.hpp"
#include "CgiProcessor.hpp"
#include "Classifier.hpp"
#include "StaticProcessor.hpp"